/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "Stm/Std/IfxStm.h"

/*
 * TriBoard TC2X7 V1.0 - 8 user LEDs (active LOW: LOW=ON, HIGH=OFF)
 * All on PORT 33: pins 6 (LSB) ... 13 (MSB)
 *
 * BLINK_TICKS: STM ticks between LED counter steps.
 *   At 200 MHz STM => 20 000 000 ticks = 100 ms per step
 */
#define BLINK_TICKS  20000000UL

/*
 * WDT_RELOAD: CPU0 watchdog reload (16-bit up-counter, overflows at 0x10000).
 *   f_WDT = fSPB/16384 = 100 MHz/16384 ~= 6104 Hz  (T ~= 163.84 us/tick)
 *   0x8000 => 32768 ticks => ~5369 ms  (well above the 100 ms ISR period)
 */
#define WDT_RELOAD   0x8000U

/* STM0 comparator interrupt priority (1-255, must be unique in the system) */
#define STM0_ISR_PRIO  10

/* -------------------------------------------------------------------------
 * Globals
 * ---------------------------------------------------------------------- */
IfxCpu_syncEvent      cpuSyncEvent = 0;
static IfxStm_CompareConfig stmConfig;

/* Binary counter displayed on LEDs. Resets to 0 on any HW reset (incl. WDT).
 * Visible in the debugger Watch window as symbol 'blinkCount'. */
volatile uint32 blinkCount = 0;

/* -------------------------------------------------------------------------
 * LED update — called from the STM ISR every BLINK_TICKS
 * ---------------------------------------------------------------------- */
static void updateLeds(void)
{
    uint8 pin;
    /* Show blinkCount as 8-bit binary: P33.6 = bit0 (LSB), P33.13 = bit7 (MSB) */
    for (pin = 0; pin < 8; pin++)
    {
        if (blinkCount & (1u << pin))
            IfxPort_setPinLow(&MODULE_P33,  (uint8)(pin + 6));  /* bit set   -> LED ON  */
        else
            IfxPort_setPinHigh(&MODULE_P33, (uint8)(pin + 6));  /* bit clear -> LED OFF */
    }
    blinkCount = (blinkCount + 1u) & 0xFFu;  /* 0-255, wraps automatically */
}

/* -------------------------------------------------------------------------
 * STM0 Compare-0 ISR  (fires every BLINK_TICKS ticks)
 * ---------------------------------------------------------------------- */
IFX_INTERRUPT(stm0Isr, 0, STM0_ISR_PRIO)
{
    /* Clear the compare flag so the interrupt line is de-asserted */
    IfxStm_clearCompareFlag(&MODULE_STM0, stmConfig.comparator);

    /* Schedule next interrupt relative to NOW (current STM value).
     * Using getLower()+BLINK_TICKS instead of increaseCompare() means the ISR
     * always recovers correctly after a debugger halt, because increaseCompare()
     * adds to the old (possibly stale) compare value which may already be in
     * the past, causing the next match to be missed until the 32-bit timer
     * wraps (~21 seconds at 200 MHz). */
    IfxStm_updateCompare(&MODULE_STM0, stmConfig.comparator,
                         IfxStm_getLower(&MODULE_STM0) + BLINK_TICKS);

    /* Update the LED binary counter */
    updateLeds();
}

/* -------------------------------------------------------------------------
 * STM0 interrupt initialisation
 * ---------------------------------------------------------------------- */
static void initStmInterrupt(void)
{
    IfxStm_initCompareConfig(&stmConfig);       /* fill with defaults           */
    stmConfig.ticks           = BLINK_TICKS;    /* interrupt period             */
    stmConfig.triggerPriority = STM0_ISR_PRIO;  /* must match IFX_INTERRUPT()   */
    stmConfig.typeOfService   = IfxSrc_Tos_cpu0;/* route to CPU0                */
    IfxStm_initCompare(&MODULE_STM0, &stmConfig);
}

/* -------------------------------------------------------------------------
 * Core 0 entry point
 * ---------------------------------------------------------------------- */
void core0_main(void)
{
    uint8  pin;
    uint16 wdtPassword;

    IfxCpu_enableInterrupts();

    /* Keep CPU0 watchdog ENABLED — service it in the while(1) loop */
    wdtPassword = IfxScuWdt_getCpuWatchdogPassword();
    IfxScuWdt_changeCpuWatchdogReload(wdtPassword, WDT_RELOAD);

    /* Safety watchdog not used in this example */
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Configure P33.6 - P33.13 as push-pull outputs, all OFF initially */
    for (pin = 6; pin <= 13; pin++)
    {
        IfxPort_setPinMode(&MODULE_P33, pin, IfxPort_Mode_outputPushPullGeneral);
        IfxPort_setPinHigh(&MODULE_P33, pin);
    }

    /* Start STM0 compare interrupt — LED updates happen in stm0Isr() */
    initStmInterrupt();

    /* Sync all cores before entering the main loop */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    /* Main loop: nothing to do except service the watchdog.
     * All LED work is done inside the STM0 ISR. */
    while(1)
    {
        IfxScuWdt_serviceCpuWatchdog(wdtPassword);
    }
}
