/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "Stm/Std/IfxStm.h"

/*
 * LED PORT SCANNER - finds the correct LED pin automatically.
 * Each candidate port pin is toggled 3 times with 1 s pauses.
 * Watch which physical LED blinks, note the port printed on the PCB,
 * then tell the port name so the final code can be written.
 *
 * Candidates tested (all active-low, i.e. LOW = ON):
 *   P10.2  (TC275 TriBoard SB)
 *   P20.11, P20.12, P20.13, P20.14  (TC3X7 TriBoard D306-D309)
 *   P33.4,  P33.5,  P33.6,  P33.7   (TC3X7 TriBoard D302-D305)
 *   P13.0,  P13.1,  P13.2,  P13.3   (Application Kit D107-D110)
 */

/*
 * TriBoard TC2X7 V1.0 - 8 user LEDs (active LOW: LOW=ON, HIGH=OFF)
 * All on PORT 33: pins 6, 7, 8, 9, 10, 11, 12, 13
 *
 * BLINK_TICKS = 50 000 000 STM ticks (no frequency calculation needed):
 *   At 100 MHz STM => 500 ms per toggle
 *   At 200 MHz STM => 250 ms per toggle
 */
#define BLINK_TICKS  20000000UL

/*
 * WDT_RELOAD: reload value for CPU0 watchdog (16-bit up-counter, overflows at 0x10000).
 *
 * Timeout = (0x10000 - WDT_RELOAD) / f_WDT
 *   f_WDT  = fSPB / 16384 = 100 MHz / 16384 ~= 6104 Hz  (T ~= 163.84 us/tick)
 *   0x8000 => (0x10000 - 0x8000) = 32768 ticks => ~5369 ms (~21 blinks at 250 ms each)
 *   0xC000 => (0x10000 - 0xC000) = 16384 ticks => ~2684 ms (~10 blinks)
 *   0x0000 => (0x10000 - 0x0000) = 65536 ticks => ~10737 ms (~42 blinks)
 *
 * Rule: timeout must be larger than the worst-case while(1) iteration time.
 */
#define WDT_RELOAD   0x8000U

IfxCpu_syncEvent cpuSyncEvent = 0;

/* Counts every LED toggle.  Resets to 0 on any hardware reset (incl. WDT).
 * Watch this in the debugger: if the WDT fires you will see it jump back to 0. */
volatile uint32 blinkCount = 0;

void core0_main(void)
{
    uint8  pin;
    uint16 wdtPassword;

    IfxCpu_enableInterrupts();

    /* Read CPU0 watchdog password — keep the watchdog ENABLED (do not disable it) */
    wdtPassword = IfxScuWdt_getCpuWatchdogPassword();

    /* Default REL=0xFFFC gives only ~655 us timeout — far too short for a 250ms loop.
     * Change reload to WDT_RELOAD (0xC000) => ~2684 ms timeout. */
    IfxScuWdt_changeCpuWatchdogReload(wdtPassword, WDT_RELOAD);

    /* Safety watchdog is not used in this example — disable it */
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Configure P33.6 - P33.13 as push-pull outputs */
    for (pin = 6; pin <= 13; pin++)
    {
        IfxPort_setPinMode(&MODULE_P33, pin, IfxPort_Mode_outputPushPullGeneral);
        IfxPort_setPinHigh(&MODULE_P33, pin);   /* LED OFF initially */
    }

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    while(1)
    {
        /* Service (kick) CPU0 watchdog — must be called before the timer expires */
        IfxScuWdt_serviceCpuWatchdog(wdtPassword);

        IfxStm_waitTicks(&MODULE_STM0, BLINK_TICKS);

        /* Display blinkCount as 8-bit binary on LEDs (active-low: LOW=ON, HIGH=OFF).
         * P33.6 = bit0 (LSB) ... P33.13 = bit7 (MSB).
         * Counter wraps 0-255 then repeats. */
        for (pin = 0; pin < 8; pin++)
        {
            if (blinkCount & (1u << pin))
                IfxPort_setPinLow(&MODULE_P33,  pin + 6);   /* bit set   → LED ON  */
            else
                IfxPort_setPinHigh(&MODULE_P33, pin + 6);   /* bit clear → LED OFF */
        }

        blinkCount = (blinkCount + 1u) & 0xFFu;  /* 0-255 counter, resets to 0 on WDT/HW reset */
    }
}
